# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-24 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_itemcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateField()),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.UserProfile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='AssignmentComment',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AlterField(
            model_name='assignmentcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Assignment'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
