# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-25 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181124_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentcomment',
            old_name='description',
            new_name='Inference',
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='excel_sheet',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
