# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-25 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20181125_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentcomment',
            old_name='Inference',
            new_name='inference',
        ),
    ]
