# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-25 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20181125_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcomment',
            name='inference',
            field=models.TextField(help_text='Upload the observation Table excel file here', max_length=1000),
        ),
    ]
