# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-25 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20181125_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcomment',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
