# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-25 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_assignmentcomment_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Rmax',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Rmin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='autocheck',
            field=models.BooleanField(default=False),
        ),
    ]
