# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-25 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_assignmentcomment_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcomment',
            name='autocheck',
            field=models.BooleanField(default=True),
        ),
    ]
