# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-20 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter assignment number(e.g. Experiment 1)', max_length=200)),
            ],
        ),
    ]
