# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-20 22:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('user_year', models.CharField(choices=[('1st', '1st Year Student'), ('2nd', '2nd Year Student'), ('3rd', 'Third Year Student'), ('4th', '4th Year Student'), ('phd', 'PHD'), ('fac', 'Faculty')], default='1st', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_data', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='Aim',
            field=models.CharField(default='Perform the following', max_length=500),
        ),
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Assignment'),
        ),
    ]
